/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newrsa;

import java.awt.Toolkit;
import java.awt.datatransfer.*;

import java.math.BigInteger;
import java.util.Random;
import java.util.Set;

/**
 *
 * @author TANIA
 */
public class rsa extends javax.swing.JFrame  implements ClipboardOwner{

    /**
     * Creates new form rsa
     */
    public rsa() {
        initComponents();
        JP_generar.setVisible(true);
        JP_cifrar.setVisible(false);
        JP_decifrar.setVisible(false);
        JT_publica.setLineWrap(true);
        TF_privada.setLineWrap(true);
        areaOrigen.setLineWrap(true);
      JT_clave_publica.setLineWrap(true);
      areaDestino.setLineWrap(true);
      JT_texto_cifrado.setLineWrap(true);
      claveprivada.setLineWrap(true);
      jTextArea1.setLineWrap(true);
        /* se crea en cifrar;
        JT_clave_publica.setLineWrap(true) se crea en cifrar;
        areaDestino.setLineWrap(true) se crea en cifrar;
       se crea en desifrar;
      claveprivada.setLineWrap(true) se crea en decifrar;
      jTextArea1.setLineWrap(true); se crea en descifrar
        */
    }
String item="";
 int tamPrimo;
    BigInteger n, q, p;
    BigInteger totient;
    BigInteger e, d;
private BigInteger[] textoCifrado;
private BigInteger[] pilanueva;
private BigInteger[] big;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        JP_generar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CB_tamaño = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        B_copiar_privada = new javax.swing.JButton();
        B_copiar_publica = new javax.swing.JButton();
        B_generar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_publica = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TF_privada = new javax.swing.JTextArea();
        JP_cifrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaOrigen = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaDestino = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        JT_clave_publica = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        JP_decifrar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        JT_texto_cifrado = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        claveprivada = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_generar = new javax.swing.JMenu();
        JM_cifrar = new javax.swing.JMenu();
        JM_descifrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tamaño clave");

        CB_tamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione tamaño", "512", "1024", "2048", "4096" }));
        CB_tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_tamañoActionPerformed(evt);
            }
        });

        jLabel2.setText("Clave publica");

        jLabel3.setText("Clave privada");

        B_copiar_privada.setText("Copiar");
        B_copiar_privada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_copiar_privadaActionPerformed(evt);
            }
        });

        B_copiar_publica.setText("Copiar");
        B_copiar_publica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_copiar_publicaActionPerformed(evt);
            }
        });

        B_generar.setText("Generar");
        B_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_generarActionPerformed(evt);
            }
        });

        JT_publica.setColumns(20);
        JT_publica.setRows(5);
        jScrollPane1.setViewportView(JT_publica);

        TF_privada.setColumns(20);
        TF_privada.setRows(5);
        jScrollPane2.setViewportView(TF_privada);

        javax.swing.GroupLayout JP_generarLayout = new javax.swing.GroupLayout(JP_generar);
        JP_generar.setLayout(JP_generarLayout);
        JP_generarLayout.setHorizontalGroup(
            JP_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_generarLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(91, 91, 91))
            .addGroup(JP_generarLayout.createSequentialGroup()
                .addGroup(JP_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_generarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_generarLayout.createSequentialGroup()
                        .addGroup(JP_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_generarLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JP_generarLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(CB_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JP_generarLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(B_generar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_generarLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(B_copiar_publica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_copiar_privada)
                .addGap(92, 92, 92))
        );
        JP_generarLayout.setVerticalGroup(
            JP_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_generarLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(B_generar)
                .addGap(18, 18, 18)
                .addGroup(JP_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_generarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_generarLayout.createSequentialGroup()
                        .addComponent(B_copiar_privada)
                        .addContainerGap())
                    .addComponent(B_copiar_publica, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jLabel5.setText("Digite texto a cifrar");

        jLabel6.setText("Digite clave pública");

        jLabel11.setText("Texto cifrado");

        jButton1.setText("Cifrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        areaOrigen.setColumns(20);
        areaOrigen.setRows(5);
        jScrollPane3.setViewportView(areaOrigen);

        areaDestino.setColumns(20);
        areaDestino.setRows(5);
        jScrollPane4.setViewportView(areaDestino);

        JT_clave_publica.setColumns(20);
        JT_clave_publica.setRows(5);
        jScrollPane5.setViewportView(JT_clave_publica);

        jButton3.setText("copiar cifrado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_cifrarLayout = new javax.swing.GroupLayout(JP_cifrar);
        JP_cifrar.setLayout(JP_cifrarLayout);
        JP_cifrarLayout.setHorizontalGroup(
            JP_cifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_cifrarLayout.createSequentialGroup()
                .addGroup(JP_cifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_cifrarLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel5))
                    .addGroup(JP_cifrarLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JP_cifrarLayout.createSequentialGroup()
                .addGroup(JP_cifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JP_cifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JP_cifrarLayout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addGroup(JP_cifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(JP_cifrarLayout.createSequentialGroup()
                                    .addComponent(jButton3)
                                    .addGap(87, 87, 87)
                                    .addComponent(jButton1))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(JP_cifrarLayout.createSequentialGroup()
                            .addGap(205, 205, 205)
                            .addComponent(jLabel6))))
                .addGap(0, 119, Short.MAX_VALUE))
        );
        JP_cifrarLayout.setVerticalGroup(
            JP_cifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_cifrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(JP_cifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jLabel12.setText("Digite texto cifrado");

        jLabel13.setText("Digite clave privada");

        jLabel14.setText("Texto descifrado");

        jButton2.setText("Decifrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        JT_texto_cifrado.setColumns(20);
        JT_texto_cifrado.setRows(5);
        jScrollPane8.setViewportView(JT_texto_cifrado);

        claveprivada.setColumns(20);
        claveprivada.setRows(5);
        jScrollPane9.setViewportView(claveprivada);

        jButton4.setText("Copiar Descifrado");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_decifrarLayout = new javax.swing.GroupLayout(JP_decifrar);
        JP_decifrar.setLayout(JP_decifrarLayout);
        JP_decifrarLayout.setHorizontalGroup(
            JP_decifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_decifrarLayout.createSequentialGroup()
                .addGroup(JP_decifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_decifrarLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(JP_decifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JP_decifrarLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(139, 139, 139)
                                .addComponent(jButton4))))
                    .addGroup(JP_decifrarLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel13)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JP_decifrarLayout.createSequentialGroup()
                .addGroup(JP_decifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_decifrarLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel12))
                    .addGroup(JP_decifrarLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel14))
                    .addGroup(JP_decifrarLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(JP_decifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JP_decifrarLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );
        JP_decifrarLayout.setVerticalGroup(
            JP_decifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_decifrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_decifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(46, 46, 46))
            .addGroup(JP_decifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JP_decifrarLayout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );

        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });

        JM_generar.setText("Generar");
        JM_generar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JM_generarMouseClicked(evt);
            }
        });
        JM_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_generarActionPerformed(evt);
            }
        });
        jMenuBar1.add(JM_generar);

        JM_cifrar.setText("Cifrar");
        JM_cifrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JM_cifrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(JM_cifrar);

        JM_descifrar.setText("Descifrar");
        JM_descifrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JM_descifrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(JM_descifrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_generar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JP_cifrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JP_decifrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_generar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JP_cifrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JP_decifrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_tamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_tamañoActionPerformed
        // TODO add your handling code here:
        item=CB_tamaño.getSelectedItem().toString();
        if(item=="512"){
            tamPrimo=512;
        }
         if(item=="1024"){
            tamPrimo=1024;
        }
          if(item=="2048"){
            tamPrimo=2048;
        }
           if(item=="4096"){
            tamPrimo=4096;
        }
        System.out.println(""+item);
    }//GEN-LAST:event_CB_tamañoActionPerformed

    private void B_copiar_publicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_copiar_publicaActionPerformed
        // TODO add your handling code here:
        cliccopy(JT_publica.getText());
    }//GEN-LAST:event_B_copiar_publicaActionPerformed

    private void JM_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_generarActionPerformed
        // TODO add your handling code here:
        System.out.println("g");
    }//GEN-LAST:event_JM_generarActionPerformed

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked
        // TODO add your handling code here:
         System.out.println("g");
    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void JM_generarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JM_generarMouseClicked
        // TODO add your handling code here:
         System.out.println("generar");
          JP_generar.setVisible(true);
          JP_cifrar.setVisible(false);
        JP_decifrar.setVisible(false);
    }//GEN-LAST:event_JM_generarMouseClicked

    private void JM_cifrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JM_cifrarMouseClicked
        // TODO add your handling code here:
         System.out.println("cifrar");
         JP_generar.setVisible(false);
           JP_cifrar.setVisible(true);
        JP_decifrar.setVisible(false);
    }//GEN-LAST:event_JM_cifrarMouseClicked

    private void JM_descifrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JM_descifrarMouseClicked
        // TODO add your handling code here:
         System.out.println("descifrar");
          JP_generar.setVisible(false);
            JP_cifrar.setVisible(false);
        JP_decifrar.setVisible(true);
    }//GEN-LAST:event_JM_descifrarMouseClicked

    private void B_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_generarActionPerformed
        // TODO add your handling code here:
        
         p = new BigInteger(tamPrimo, 10, new Random()); 
      do q = new BigInteger(tamPrimo, 10, new Random());
           while(q.compareTo(p)==0);
      
        System.out.println("p es="+p);
        System.out.println("q es="+q);
        generaClaves(p,q);
        System.out.println("e vieja es="+e.toString());
        
        //clave publica e,n
    JT_publica.setText(e.toString()+"l"+n.toString());
    //clave privada d,n
    TF_privada.setText(d.toString()+"l"+n.toString());
    
    }//GEN-LAST:event_B_generarActionPerformed

    private void B_copiar_privadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_copiar_privadaActionPerformed
        // TODO add your handling code here:
        cliccopy(TF_privada.getText());
        
        
    }//GEN-LAST:event_B_copiar_privadaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        detectarclave(JT_clave_publica.getText());
        
          textoCifrado = encripta(areaOrigen.getText());
                    areaDestino.setText("");
                   
                    for(int i=0; i<textoCifrado.length; i++){
                    areaDestino.append(textoCifrado[i].toString()+"l");
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        separador(JT_texto_cifrado.getText());
        detectarclaveprivada(claveprivada.getText());
        String recuperarTextoPlano = desencripta(big);
                  
                    
                    jTextArea1.setText(recuperarTextoPlano);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cliccopy(areaDestino.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        claveprivada.setText("");
        JT_texto_cifrado.setText("");
        JT_clave_publica.setText("");
        areaOrigen.setText("");
        areaDestino.setText("");
        JT_publica.setText("");
        TF_privada.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    public void separador(String texto){
  String[] separacion;
  
  separacion=texto.split("l");
           big = new BigInteger[separacion.length];
      for (int i = 0; i < separacion.length; i++) {
           big[i]=new BigInteger(separacion[i]);
      } 
  }
    public void detectarclave(String texto){
       String[] separacion;
   //texto=JT_clave_publica.getText();
   separacion=texto.split("l");
   e=new BigInteger(separacion[0]);
   n=new BigInteger(separacion[1]);
       System.out.println("e es "+separacion[0]+" n es "+separacion[1]);
   }
    public void detectarclaveprivada(String texto){
       String[] separacion;
   //texto=JT_clave_publica.getText();
   separacion=texto.split("l");
   d=new BigInteger(separacion[0]);
   n=new BigInteger(separacion[1]);
       System.out.println("d es "+separacion[0]+" n es "+separacion[1]);
   }
    public void generaClaves(BigInteger p,BigInteger q)
    {
        // n = p * q
        n = p.multiply(q);
        // toltient = (p-1)*(q-1)
        totient = p.subtract(BigInteger.valueOf(1));
        totient = totient.multiply(q.subtract(BigInteger.valueOf(1)));
        // Elegimos un e coprimo de y menor que n
        do e = new BigInteger(2 * tamPrimo, new Random());
            while((e.compareTo(totient) != -1) || (e.gcd(totient).compareTo(BigInteger.valueOf(1)) != 0));
        // d = e^1 mod totient
        d = e.modInverse(totient);
       /* System.out.println("n es:"+n);
        System.out.println("e es:"+e);*/
        System.out.println("d es:"+d);
        
    }
   public void cliccopy(String texto){
   StringSelection txt=new StringSelection(texto);
   Toolkit.getDefaultToolkit().getSystemClipboard().setContents(txt,this);
   }
   
   
    public BigInteger[] encripta(String mensaje)
    {
        int i;
        byte[] temp = new byte[1];
        byte[] digitos = mensaje.getBytes();
        BigInteger[] bigdigitos = new BigInteger[digitos.length];
        
        for(i=0; i<bigdigitos.length;i++){
            temp[0] = digitos[i];
            bigdigitos[i] = new BigInteger(temp);
        }
        
        BigInteger[] encriptado = new BigInteger[bigdigitos.length];
        
        for(i=0; i<bigdigitos.length; i++)
            encriptado[i] = bigdigitos[i].modPow(e,n);
        
        return(encriptado);
    }
    public String desencripta(BigInteger[] encriptado) {
        BigInteger[] desencriptado = new BigInteger[encriptado.length];
        
        for(int i=0; i<desencriptado.length; i++)
            desencriptado[i] = encriptado[i].modPow(d,n);
        
        char[] charArray = new char[desencriptado.length];
        
        for(int i=0; i<charArray.length; i++)
            charArray[i] = (char) (desencriptado[i].intValue());
        
        return(new String(charArray));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rsa().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_copiar_privada;
    private javax.swing.JButton B_copiar_publica;
    private javax.swing.JButton B_generar;
    private javax.swing.JComboBox<String> CB_tamaño;
    private javax.swing.JMenu JM_cifrar;
    private javax.swing.JMenu JM_descifrar;
    private javax.swing.JMenu JM_generar;
    private javax.swing.JPanel JP_cifrar;
    private javax.swing.JPanel JP_decifrar;
    private javax.swing.JPanel JP_generar;
    private javax.swing.JTextArea JT_clave_publica;
    private javax.swing.JTextArea JT_publica;
    private javax.swing.JTextArea JT_texto_cifrado;
    private javax.swing.JTextArea TF_privada;
    private javax.swing.JTextArea areaDestino;
    private javax.swing.JTextArea areaOrigen;
    private javax.swing.JTextArea claveprivada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void lostOwnership(Clipboard clpbrd, Transferable t) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
